version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-login1
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Strong123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login1-app
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=LOGIN1DB;Trusted_Connection=True;TrustServerCertificate=True;


volumes:
  mssql_data:
